### ISSUE TITLE
ImportError: cannot import name 'get_bilinear_index' from 'functions'

### ISSUE THREAD

**Issue by sendjasni** [FutureShow/Gnomonic-Projection#1]
I'm facing this error when running the code using Python3:

`ImportError: cannot import name 'get_bilinear_index' from 'functions'`

I don't have much experience, so I couldn't debug it myself.

**Comment by FutureShow** [comment]
I apologize to you that I solve the problem now. If you have any questions, please feel free to contact me. :)
